# Generated by Django 2.2.3 on 2019-07-24 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190724_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
